### ISSUE TITLE
Квест "Вредная привычка": мгновенный спор с Люсией

### ISSUE THREAD

**Issue by KorobetskayaAA** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#28]
Надя и Люсия спорят сразу, а должно быть до следующего дня

**Comment by NastasSanna** [comment]
+ Люсия и Надя коротко переговорят вечером того же дня 21:40-21:45
+ на следующий день разговор состоится в 9:00, когда Надя выйдет подышать свежим воздухом
+ исправлены записи в журнал
