### ISSUE TITLE
Квест "Вредная привычка": диалог с Боркой

### ISSUE THREAD

**Issue by KorobetskayaAA** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#29]
После оплаты информации диалог не начинается сразу, нужно сначала прекратить разговор
если выбрать вариант "а может договоримся" пропадает диалог об оплате входа

**Comment by KorobetskayaAA** [comment]
После выбора "Это что, шутка такая?" остается только вариант "Что, мало? Могу еще добавить уколов шпагой."

**Comment by KorobetskayaAA** [comment]
Диалог DIA_Borka_Sarah_TellInsider разделить на два.
**ОЗВУЧКА:**
Фразу:
DIA_Borka_Sarah_TellInsider_16_05	//Это то, что нужно! Пропусти меня, я с ней поговорю.
разрезать на две:
DIA_Borka_Sarah_TellInsider_16_05	//Это то, что нужно!
DIA_Borka_Sarah_LetMeInToLucia_16_00	//Пропусти меня, я с ней поговорю.

**Comment by TheG0vernor** [comment]
Будет выполнено.

**Comment by NastasSanna** [comment]
+ Соня прервет разговор, если перепутать ее с Люсией
+ Постоянный диалог с Надей "Эй, это же я, Сара, твоя подруга детства."
+ У Эдды диалог "Как поживаешь?" только после приветствия
+ Надя не должна слышать разговоры с Боркой и Люсией
