### ISSUE TITLE
Убийство соперников: когда должна появляться охрана?

### ISSUE THREAD

**Issue by KorobetskayaAA** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#41]
После 2 смертей появляться, после 4 атаковать без предупреждения?

**Comment by TheG0vernor** [comment]
Нет, все не так. После 1 смертей появляться, после 3 атаковать без предупреждения.

**Comment by KorobetskayaAA** [comment]
Не согласна. Рано. И кроме охраны, они после каждой смерти просто усиливаются.
Еще можно добавить промежуточный вариант, что охранники не нападают, но при виде ГГ предупредительно достают оружие.

**Comment by TheG0vernor** [comment]
А грибник не уйдёт, пока охранник будет мечом на ГГ предупредительно размахивать? Как бы не навредить безопасности Грибника этим, бесспорно интересным, нововведением. Ну что же, если Грибники будут усиливаться (или уже усиливаются, только я не замечаю) после каждой смерти, пускай будет 2 и 4.

**Comment by KorobetskayaAA** [comment]
Вместе с охранником будут стоять и грозно глядеть на ГГ, пока тот не уйдет. А если ГГ тоже достанет любое оружие, тогда нападут.

**Comment by TheG0vernor** [comment]
Превосходно. Давай после 3.
