### ISSUE TITLE
Эрол: гробокопательство

### ISSUE THREAD

**Issue by KorobetskayaAA** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#46]
Если по ОДНОМУ разу копнуть каждую могилку, то всё путём. Но, как только попробуем повторить - начинают пропадать кирки из инвентаря. Причём, есть один нюанс: если мы попытаемся второй раз разворошить пустую могилку (нижняя по склону) - Эрол просто пожмёт плечами, а из инвентаря пропадёт кирка. Повторим и всё также. То же происходит и с могилкой в которой табличка - жим плечами и минус кирка. Но, когда второй раз попробуем ковырнуть захоронение с кольцом - уже иная история: показывается снова анимация, как Эрол усердно долбит землю (как при первых раскопах), затем высвечивается надпись "Здесь больше ничего нет."
Продолжим ковырять в третий раз и Эрол снова знакомо начнёт пожимать плечами и будут исчезать кирки. Нельзя ли сделать, чтобы, когда мы захотим второй-третий-десятый раз распотрошить захоронения, дабы не терять время, НЕ ПОКАЗЫВАТЬ анимацию, как Эрол снова долбит киркой, а оставить только пожимание плечами, но с высвечиванием надписи, что "больше ничего нет", "я уже тут ковырялся", "я не буду по сто раз рыться в этих гнилых костях" и т. п. И, разумеется, было бы здорово, чтобы перестали исчезать кирки. *right*

**Comment by NastasSanna** [comment]
С ZEN-ом все в порядке: UseWithItem пуст, ConditionFunc: CANGETTREASURE

**Comment by NastasSanna** [comment]
Корректная анимация + индивидуальные conditionFunc
