### ISSUE TITLE
Косой Гарри

### ISSUE THREAD

**Issue by KorobetskayaAA** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#5]
Кардиф упоминает Косого Гарри, которого прихватило в холодном море. Добавить NPC или дать имя существующему

**Comment by TheG0vernor** [comment]
КМК лучше дать имя существующему :)

**Comment by NastasSanna** [comment]
Это в плане идеи, если время останется. Сделать после того, как узнаем слух, одну фразочку вроде "Как ты после купания?"

**Comment by TheG0vernor** [comment]
Боже упаси, ещё фразочку? Адепт с Кертаксом до сих пор те 2 реплики не могут озвучить :)

**Comment by NastasSanna** [comment]
Не переживай, вряд ли руки дойдут.

**Comment by NastasSanna** [comment]
Не будет реализовано.
