### ISSUE TITLE
Тальбину не спится..

### ISSUE THREAD

**Issue by TheG0vernor** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#51]
В его утеплённой хижине.. При том, что Эрол в ней спит как младенец.
В тёпленькой пещере Сагитты. Не только Тальбину.

**Comment by KorobetskayaAA** [comment]
Не поняла. При игре за Талбина не получается спать? Или конкурент-Талбин не спит? И что с Сагиттой?

**Comment by TheG0vernor** [comment]
Он замерзает - слишком холодно..

2017-10-10 19:39 GMT+07:00 Анастасия Александровна Коробецкая <
notifications@github.com>:

**Comment by KorobetskayaAA** [comment]
А, ясно.

1. Проверить, привязан ли домик охотников и пещера Сагитты к гильдии GIL_OUT.
2. Выполняется ли проверка по привязке к NPC.

**Comment by NastasSanna** [comment]
Добавлен портал в пещере Сагитты SAGITTACAVE
