### ISSUE TITLE
Вероятность сбора грибов соперниками: упростить формулу

### ISSUE THREAD

**Issue by NastasSanna** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#57]

**Comment by TheG0vernor** [comment]
А оно надо? Мне кажется формула и сейчас хороша.

**Comment by NastasSanna** [comment]
Надо. Я сама в ней путаюсь. Например, нормальная активность соперников = 100 (процентов). Очень низкая = 10, Невозможная = 400. Думаешь, на невозможной соперники собирают в 4 раза больше грибов, а на очень низкой - в 10 раз меньше? Ничего подобного. Формула сильно нелинейная, во сколько раз получается разница - я сама не могу точно сказать.

**Comment by NastasSanna** [comment]
[Вероятности.xlsx](https://github.com/NastasSanna/Mushroomers-Gothic-II-NoR-Mod-/files/1428722/default.xlsx)
