### ISSUE TITLE
Файлы с пробелами в имени

### ISSUE THREAD

**Issue by NastasSanna** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#58]
DIA_DARON_DONATE50_07_00 .WAV
DIA_DRAGOMIR_ABOUTRUINS_07_00 .WAV
DIA_DRAGOMIR_UAWELCOME_07_01 .WAV
DIA_ENGROM_FOLLOWME_TALBIN_07_00 .WAV
DIA_ENGROM_TALBIN_FINAL_LOST_03_01 .WAV
DIA_FELLAN_SHOWHAMMER_07_04 .WAV
DIA_GRIMBALD_ORCSDEAD_07_00 .WAV
DIA_HALVOR_YOURPOST_MONEYFIRST100_07_00 .WAV
DIA_IGNAZ_ASKRECIPE_ISITSAFE_07_00 .WAV
DIA_LUTERO_MRTRADE_07_00 .WAV
DIA_MALETH_ILLKILLWOLVES_07_00 .WAV
DIA_NICLAS_EXCHANGE_07_00 .WAV
DIA_ROSI_HUSBAND_OTHERS_07_00 .WAV
DIA_SAGITTA_POISONED_07_06 .WAV
DIA_TALBIN_AFTER_SHADOWFUR_10_02 .WAV
DIA_TROCAR_MSGFROMBARTOK_07_00 .WAV
DIA_TROCAR_TALBIN_WHYALONE_07_00 .WAV
DIA_TROCAR_WHITESHADOWBEAST_07_07 .WAV
SVM_7_GOODVICTORY .WAV
SVM_7_NEVERHITMEAGAIN .WAV
SVM_7_SHEEPKILLER .WAV
SVM_7_STOPMAGIC .WAV
SVM_7_WHATSTHISSUPPOSEDTOBE .WAV
SVM_7_WILLYOUSTOPFIGHTING .WAV
SVM_7_YOUASKEDFORIT .WAV

**Comment by TheG0vernor** [comment]
Чудно. Исправил.
