### ISSUE TITLE
Ночные искры как приправа

### ISSUE THREAD

**Issue by TheG0vernor** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#60]
Из книги про грибы мы узнаём, что ночные искры используются гурманами как острая специя. Почему бы не добавить возможность принести их Грому после прочтения книги? Я честно говоря других приправ не нашёл.

**Comment by NastasSanna** [comment]
Да, была такая мысль. Сейчас можно купить красный жгучий перец и его отдать.

Для ночных искр надо условие, что игрок прочитал соответствующую страницу книги.

**Comment by TheG0vernor** [comment]
Кто же его продает? Ни Зурис, ни Саландрил ни даже Лютеро не имеют его в
продаже. Ладно, не говори. Раз есть в продаже, я найду его.

Реплики новые добавляться будут или не обязательны?

**Comment by NastasSanna** [comment]
В городе его не достать. 

Да, реплики понадобятся. Каждому ГГ и Грому. Что-то вроде:
Руперт/Одо
DIA_Grom_SpicesNSparkles_03_00	//Эти грибы можно использовать как приправу - они острые.
Талбин
DIA_Grom_SpicesNSparkles_07_00	//Эти грибы можно использовать как приправу. Они острые как добрый перец.
Эрол
DIA_Grom_SpicesNSparkles_10_00	//Эти грибы можно использовать как приправу. Они острые как добрый перец.
Тилл
DIA_Grom_SpicesNSparkles_14_00	//Эти грибы можно использовать как приправу - они острые.
Сара/Елена
DIA_Grom_SpicesNSparkles_16_00	//Эти грибы можно использовать как приправу - они остренькие.
Гром
DIA_Grom_SpicesNSparkles_08_01	//Попробуем! Никогда не приправлял грибы грибами.
Дальше фразы про награду как и после перца.

**Comment by TheG0vernor** [comment]
Отправил на доозвучку шестерым актёрам.

**Comment by NastasSanna** [comment]
Озвучку не нашла. Закрываю.

**Comment by NastasSanna** [comment]
Грибы можно отдать, если их попробовать или прочитать про них в книге.
