### ISSUE TITLE
В пещере под Солнечным кругом идет дождь?

### ISSUE THREAD

**Issue by NastasSanna** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#65]
И вода где-то появляется. Проверить целостность меша.

**Comment by TheG0vernor** [comment]
Если не ошибаюсь, во всех пещерах под рендером ДХ11 идёт дождь.

**Comment by NastasSanna** [comment]
Да, без DX11 все нормально. Но у меня в одной из старых версий там немного шов разошелся, пока не стала убирать в закрытые - проверю, все ли исправила.

**Comment by NastasSanna** [comment]
Не обнаружено.
