### ISSUE TITLE
Молитвы богам при выборе бога-покровителя?

### ISSUE THREAD

**Issue by NastasSanna** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#72]

**Comment by TheG0vernor** [comment]
Ещё информация:

"по религии: если выбираем Белиара (проверял Рупертом), то деньги за молитву можно получить только на 3 день, а все остальные жрет жизнь и шарахает молнией.
не совсем понятен такой принцип. тогда как проходя за Аданоса со второго дня получал ежедневно все плюшки от богов: и деньги от белиара, и силу/ловк от Инноса и ману, защиту от Аданоса"

**Comment by NastasSanna** [comment]
Белиару можно молиться только ночью, как и в оригинале. Днем как раз "шарахает молнией" независимо от бога-покровителя.

**Comment by TheG0vernor** [comment]
В оригинале можно молиться только ночью? Я неоднократно молился днём и получал деньги.
