### ISSUE TITLE
Сагитта: зависает при лечении

### ISSUE THREAD

**Issue by NastasSanna** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#79]
Отравление туманником, КОНЕЦ - камера остается в диалоге. Из-за эффекта? Или пропуск времени случайно вставила?

**Comment by TheG0vernor** [comment]
У меня такого не было. Тысячу раз травился туманником и лечился. У неё Готика стимовская, возможно глючная.

**Comment by NastasSanna** [comment]
А у Лоста было. Значит, не случайно, надо проверить из-за чего так получается.

**Comment by TheG0vernor** [comment]
У Лоста тоже глюк за глюком бегает и глюком подгоняет :) Но проверить надо, конечно.

**Comment by NastasSanna** [comment]
Причина до конца не ясна, но прерывание диалога сразу после лечения все исправляет.
