### ISSUE TITLE
Одо умеет снимать овечьи шкуры...

### ISSUE THREAD

**Issue by TheG0vernor** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#81]
При том, что охотничьим трофеям не обучался.

**Comment by NastasSanna** [comment]
Не умеет. Нельзя уметь снимать только овечьи шкуры. Навык общий для всех видов шкур. Откуда шкура взялась?

**Comment by TheG0vernor** [comment]
Убил овец на ферме Лобарта и у каждой увидел в инвентаре возможность снять шкуру. С волков и прочих зверей шкуры не снимались.

**Comment by NastasSanna** [comment]
Перебила всех овец на Хоринисе - ни разу не выпала. Чисто теоретически может что-то сбойнуть, что шкура не удалится из инвентаря овцы в момент смерти. Но я не представляю, с чем это может быть связано. Дай сейв.

**Comment by TheG0vernor** [comment]
Конечно http://rgho.st/7SngtMYs7

**Comment by NastasSanna** [comment]
Все охотничьи навыки выучены. ItemFeller-а или Рокфеллера вызывал? Вижу, что Рокфеллер в сейве присутствует. Он выучивает все трофеи.

**Comment by TheG0vernor** [comment]
Все ясно. Да, впервые в жизни вызвал рокфеллера и попался. Не повезло.

21 октября 2017 г., 19:31 пользователь НастасьСанна <
notifications@github.com> написал:
