### ISSUE TITLE
Назначить Парлану 24 голос

### ISSUE THREAD

**Issue by TheG0vernor** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#82]

**Comment by NastasSanna** [comment]
У меня Парлан под 2 голосом значится и записан на }{имеру. И вроде бы его голосом говорит. А универсальные реплики (вон из Монастыря!) и вовсе твои.

**Comment by NastasSanna** [comment]
Может Пирокар? Он Истаровский, но сейчас с 20 голосом.

**Comment by NastasSanna** [comment]
А СВМы лучше всего 21 подходят, мне кажется.

**Comment by TheG0vernor** [comment]
Настя Настенька Настюша, у тебя столько тикетов, а ты эту ерунду
проверяешь, с каким свм-ом лучше :) Парлан будет переозвучен, а
переозвученной версии подойдёт только 24.

2017-10-21 23:43 GMT+07:00 НастасьСанна <notifications@github.com>:

**Comment by TheG0vernor** [comment]
Универсальные реплики "Вон из монастыря!11" также начитает Истар. Голосом Парлана. Все равно там никто кроме него из магов ГГ не сцапывает.

**Comment by TheG0vernor** [comment]
Истар начитал реплики. Если голос исправлен, то можешь закрывать.
