### ISSUE TITLE
!sTaR, Faer, Taja i Naja: доработать пасхалку

### ISSUE THREAD

**Issue by NastasSanna** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#86]
Вернуть крик
Два зомби

**Comment by NastasSanna** [comment]
Бладвин атакует зомби

**Comment by TheG0vernor** [comment]
Ты же была против зомби? А теперь ещё и 2.

**Comment by TheG0vernor** [comment]
Крик тогда бы однократный сделать.

**Comment by TheG0vernor** [comment]
Ну и раз тебе захотелось править пасхалки, ещё Файр Драгон приличное время назад просил переделать его пасхалку. Я тогда отказал, мотивировав тем что работы и без того полно и пасхалки правиться не будут, подведена черта. Цитирую:

"Кстати, у меня тут есть идейка для моей пасхалки, только не знаю, возможно ли её заменить)
Очень интересная...
Заместо чиха появляется дракон, говорит "Улыбочку", раздаётся щелчок bandicam, затем "Это вам" и дракон пропадает, а в инвентаре появляется портрет персонажа.
Скрины портретов персонажей, конечно же, сам сделаю
Но, если вообще возможно заменить пасхалку 😇
Просто я понял, что моё начихание на игроков не очень хорошо смотрится)
Можно и без появление дракона, просто чтобы заместо чиха было "Улыбочку и звук bandicam", а в инвентаре появлялся портрет персонажа"

Дракончика можно взять из Пасхального мода. Он там такой славненький, маленький.

И у меня пожелание сделать у себя иммун к заморозке. Тикеты не создаю, так как не считаю правку пасхалок обязательной.

**Comment by NastasSanna** [comment]
Истар мне написал, что он против выбранной фразы - убирай, говорит, я не так хотел. Пришлось переделать. Но кричащие зомби ему не нужны, кричать будет портрет, а зомби просто появляться.

**Comment by NastasSanna** [comment]
Дракона сделаю, если он предоставит все исходники.

**Comment by NastasSanna** [comment]
От зомби отказались. Громкость немного убавить, чтобы уши не резало.

**Comment by TheG0vernor** [comment]
Истару лишь бы повыделываться. У меня есть письменное подтверждение того,
что ему своя пасхалка была "неинтересна" и он разрешает использовать любую
реплику на мой выбор. Звук "крика", который он прислал ранее, был не для
портрета, а для амулета, ГГ мог одеть его и тогда раздастся этот звук.

Я тогда отринул эту идею, т.к. на тот момент в моей голове все актеры
предполагались портретами/неписями/грибами в одной-единственной комнате, и
при клике/взгляде на них должна раздаваться реплика. Но теперь, когда есть
скрижаль Рен, которую можно читать, почему бы не сделать амулет, который
можно "надеть". И также бросить его в мир. А портрет убрать, тем более что
его он тоже не присылал. Ещё увидит портрет - напишет, что не такой хотел
:) а ты и рада расстараться для актёра, озвучившего твоё детище. И
озвучившего хорошо.

P.S. Он и текущую свою реплику не слышал. Моды он не проходит, а в
прохождении на ТыТрубе, которое он смотрел, до его портрета не дошли.

2017-10-29 17:56 GMT+07:00 НастасьСанна <notifications@github.com>:

**Comment by NastasSanna** [comment]
Я ему видео скинула. Портрет он другой уже прислал - забавное фото, кстати.

**Comment by TheG0vernor** [comment]
Добавь пож-та мое имя и фамилию в скобках после ника при записи в дневник во время разговора со мной.

**Comment by NastasSanna** [comment]
Хорошо

**Comment by NastasSanna** [comment]
Истар готов, Тайе и Найе обновила текстуры. Фразы не знаю, какие взять, поэтом не меняла. Мне и эти нравятся.
