### ISSUE TITLE
 Падающие листья над кругом камней на ферме Лобарта

### ISSUE THREAD

**Issue by KorobetskayaAA** [NastasSanna/Mushroomers-Gothic-II-NoR-Mod-#9]
Сделать отдельно PFX для двух деревьев, иначе появляются в воздухе посередине между деревьями

**Comment by NastasSanna** [comment]
Добавлены каждому дереву отдельно

Настроить pfx: больше пауза между листьями

**Comment by NastasSanna** [comment]
Теперь красиво. Можно добавить еще один вид листьев - иначе слишком много с одинаковой анимацией.
